apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: backend
          image: backend:5
          ports:
            - containerPort: 8000
