apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000  # expose frontend on host port 30000

